SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

DATASETS: [SportsMOT]
DATASET_SPLITS: [train]
INFERENCE_DATASET: SportsMOT
INFERENCE_SPLIT: val
OUTPUTS_DIR: /content/drive/MyDrive/Object_tracking
DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_sportsmot.pth
INFERENCE_MODEL: /content/drive/MyDrive/r50_deformable_detr_motip_sportsmot_trainval.pth
VIDEO_PATH: /content/drive/MyDrive/Object_tracking/samples/sample_videos/5.mp4
EPOCHS: 18
SCHEDULER_MILESTONES: [10, 16]
INFERENCE_ONLY_DETR: False
